# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "stable"

# http://docs.travis-ci.com/user/build-lifecycle/
before_script:
  - "npm install"

script:
  - "npm test"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
