# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "node"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

install:
  - npm install

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  email:
    secure: B9bQLQcE0Xd9NsBZT+oLlkrndmfe9ws99Qzswd/s8Ce5gJqWZv6/i0kG2GDuku6FTlf6AgAl2+VN2EYLRXqw5wRjX5OlvxxfHWNV2Vu4/PDUcxF6+Vcsa8A3MWPdGmTV6tDkXfOKOi4oNbJ1ERUCo98SNpNmRb7/cAmw7P5GSCNWIBx1VuTF3/t9sVj5oldA9LMDXHqKkDwe/QvG87KzzOBAq9ELwEO/jYB5O6nqHwui1Tt9GZigFQ9mKiJZEisXu+jaBMlhvpZLPT8ygDsl1mdLx4GG2uEMKm9ckjr15M5nVyI3S45V8gQGD/AiKJ3M7/BM+OMGqpKoDQFHBDQUB3uSRPwF3hFRbu48VR6i4L54barw2agY84R/dOFu2NHPlGBc8WNGQN9Q5Zotcf42BasY+zeFxHUtlco5p0E1xTeC05gPDI57R4JpGkJACG3mdgLWtd7fuehjRJ/KtOZPxgWdvgWlfENuNke2LMoKcg6kmfsZnnPqYuZe1v3Zawxl7ah7ABh4QwR5N7JhlrEXXF1liWySLubkglc4kNZyHvMGZ5pyFegkFHaiJij4ME+wcsbcGriTwXGC2gnzz1+K6VkrbCmjB20tV9DHTwQwmo6rWSeA/2S0bEWctB+oJa98nNkx/+nLnMYD8+O9iAP6pTmDNoqooMrE8b8Sb+hh+MI=
  api_key:
    secure: 1zPvzONd7H4hPFo86Y/ZyHa1cbf+7VK4ekE7BZtrIV+ETGLtKbkfiQslMdyCTrABc2fzZJufYdC7CxYEMp+6TOCrBrWFyTtLDLkE8m+as13CWABFjfNP7ePexAs0CVOKhn19s1acvJaZE4Q/aE7Fl2UiUKl4+OPJGudht2DrR6CHIjQsDM6AXbWYWOhiL+kxu9LQV0XB9bsZHeJ5AVH++xK/piHTAnOqcdQecKuZOOiOXoOA/VX+xYTetY/lECSlX/Ua2R2UQZvElJjAwMH3XXJqkFx1AEvMFFRchN262RJ+XrE08YuJG1lt1bGfMtIitmVL1IlfCrBhYdnYKP0npE5CdmKOvX1cJm0avoH9nmvyH3HOdZ+UsGmoMCpsSG5veLNqBXko8SxIMV/cTYGBaJ+0qFTXVvy7OplF3IoDJ1mwKJxW9ybJNSzb7jf+n8snBZKEGYsQfil9r5PYuA/M73tKinjdwyVAVEE+pG5KUAsHl/qEHc8qE3ypSlkM0ak9mrs74P+PTqxovM2AcV39bF+JVJgy44YRiV36g0De6xsGjXBgyV6+FuGfEuQfhxYNV/F+0ypPHK2AgyCmwznMGL+tHLoi0wmqkQhLX41w1db7W+3bRr85ArDEQ7Yjd4fZr0IR+R/LTEQrh8no/43Gi66fwbsWP0PsqpF2hbyBgO8=
  on:
    repo: wireapp/proteus.js
    tags: true
