# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "node"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

install:
  - npm install

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  email: webapp@wire.com
  api_key:
    secure: 0IHNmVSuxHJGj1jNoOrVl56RNpDEGJiFFohHl2wnIz2uZthsvE13Vuwg/2FsIAv6B7a4mlxAP6AKXIEQnh/ZHjDu2HlDMZmrubfgbRXLU4GoUP9c2EfceUdgYDj7o94M1Ll6MkydqvVDRYFs0QuNkCJ4Z11JD27wAWcLK4tZenlvpvrpP59D6X8+3sPEKK40s9BKlDkNevK03njxJE0zonnSqXyvr5zoeuO5DfU/4rP+IJoIA+lvzuHqQd+SdrYRMk8np5hL4tmHrcnpQ/ubhfdXD+ngCYqKYkkLxuXRSs5xvjCGpNVeuMR0Ik8mDP/VqLySLeTBftWo9mVIKtLaZakPURLehp3RZnqW+q8ZEU7DDqKeVbaL2h9M2xOJXkUBnFMZqEm6+YRje1rkV2+Pd5JXpDlU5MSrXAikU1HXSrDqt1gyWVoXmgEWK8ORPGEkIy6d9GZAcvlDbDu22w1VWLWaGBaA+jtmlvz1NVxwSyuzVdhtmb0mI4hqED6CpLWYbymGvTpTPKheN9kfZLW7GBfjpHdbAaRGf8rpbONkVdCLJjB4XZU/sCoyNdpDHGXkRjBbzVD3EX2W+dLBKny3B5RQc10Jp+ImtmjEPS/Tunh/9/HJTN3yxuoopE8Y2rycFnLmf4w49g9OU/7a7GM7xuLghGRmV8jV6cSGQNc7i18=
  on:
    repo: wireapp/proteus.js
    tags: true
